### PR TITLE
Converted Makefile in examples and tutorial to CMake

### PR DESCRIPTION
**Pull request by sanjosh**
CMake file follows same format as existing CMake file in tests dir.
Added examples and tutorial subdirectories to top-level CMake

Had to rename int-vector-buffer.cpp since cmake does not like target with same name in two directories (i.e. error message is "add_executable cannot create target "int-vector-buffer" because another target with the same name already exists.  The existing target is an executable created in source directory")

### CODE REVIEW

**Comment by mpetri** [comment]
so in the `build` directory I would take make int-vector-mapper and it would create `./build/examples/int-vector-mapper.x` ?

**Comment by sanjosh** [comment]
Are you asking a question about the error I mentioned above or cmake in general ?

"make int-vector-mapper" creates an executable in build/examples/ - yes

regarding error I mentioned above, cmake complains before that while creating Makefiles as seen here http://cmake.3232098.n2.nabble.com/What-is-the-preferred-way-to-avoid-quot-same-name-already-exists-quot-error-td7585687.html

**Comment by mpetri** [comment]
What is nice about the way it currently works is that I can just go into the `examples` directory and type make `xyz` and it would create a binary that I can execute. 

On the other hand having binaries in the `build` directory is more "cmake like" and cleaner I guess.

**Comment by sanjosh** [comment]
make didn't work on my machine.  Crapped out on some dependency so I changed it to cmake.

**Comment by cpockrandt** [comment]
I also support building outside the source directory since it would be much cleaner.

May I ask what the status is? Currently travis builds are failing because of some old linking of the SDSL. I would create a separate PR to remove all ``-lsdsl`` if this PR is frozen for the moment.

**Comment by simongog** [comment]
Ok, I will merge this branch and adapt the .travis file.

**Pull request merged**
