### PR TITLE
Fixing unit tests

### PR DESCRIPTION
**Pull request by cpockrandt**
- [x] search_bidirectional_test (fails when executed in parallel)
- [x] cst_byte_test and cst_int_test (failing assertions in debug mode)
- [x] fix cst_int_test with clang introduced by #59

### CODE REVIEW

**Comment by cpockrandt** [comment]
This PR resolves all bugs found by the tests. For some reason `std::sort` gives different results on osx :see_no_evil: I'm still looking into it.

Can you review this PR, @eseiler? :)

**Comment by eseiler** [comment]
LGTM,

regarding macOS: use `std::stable_sort`
seems to work for me

**Comment by cpockrandt** [comment]
Thanks! `std::stable_sort` works for me too. :nerd_face: But that doesn't make sense. There can never be values (suffixes) that are equal. :woman_shrugging:

I will change it to `std::stable_sort` anyway since it only affects the reference implementation in tests. When this is merged, you can rebase your pull requests and I'll merge them asap.

**Comment by cpockrandt** [comment]
I realized my mistake. `std::sort` compares identical elements :)

**Pull request merged**
